title: TPSIT Notes 
paginate: 5
languageCode: en-us
theme: "hugo-PaperMod" 

baseurl: https://tpsit-notes.netlify.app/

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45 

# analytics: 
    #     google:
    #         SiteVerificationTag: "XYZabc"

minify:
    disableXML: true
    minifyOutput: true

params:     
    socialIcons: # optional
        - name: "github"
          url: "https://github.com/therealgabryx/tpsit-notes"
        - name: "website"
          url: "https://www.buonarroti.tn.it/"

    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "TPSIT Notes"
    author: 5INB 2020/21 

    defaultTheme: auto
    # disableThemeToggle: true 

    # reading time 
    ShowReadingTime: true

    # show table of contents 
    ShowToc: false 

    ShowBreadCrumbs: true

languages:
    en:
        languageName: "English"
        weight: 2
        menu:
            main:
                - name: Search
                  url: search/
                  weight: 40  
                - name: Tags
                  url: tags/
                  weight: 30
                # - name: Categories
                  # url: categories/
                  # weight: 20
                - name: Home 
                  url: /
                  weight: 10
        homeInfoParams:
          Title: Hi there! 👋
          Content: Welcome to the TPSIT Cheatsheets website, written with ❤️ by Class 5INB @ ITT Buonarroti Trento.

    it:
        languageName: "Italiano"
        weight: 2
        
        menu:
            main:
                - name: Cerca
                  url: search/
                  weight: 40  
                - name: Tags
                  url: tags/
                  weight: 30
                # - name: Categorie
                  # url: categories/
                  # weight: 20
                - name: Home 
                  url: /
                  weight: 10
        homeInfoParams:
            Title: Ciao! 👋
            Content: Benvenuto nel sito degli Appunti di TPSIT, scritti con ❤️ dalla Classe 5INB @ ITT Buonarroti Trento.

outputs:
    home:
        - HTML 
        - JSON 
    

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35
 

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true